/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.io.File;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType1Font;

import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.api.IRender;
import com.indvd00m.ascii.render.elements.PseudoText;

public class App {
    private static PDFont HELVETICA;

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        IRender render = new Render();
		IContextBuilder builder = render.newBuilder();
		builder.width(120).height(13);
		builder.element(new PseudoText("It's a me, Mario"));
		ICanvas canvas = render.render(builder.build());
		String s = canvas.getText();
		System.out.println(s);

        System.out.println(new App().getGreeting());

        // PDF Box
        PDDocument helloPdf = new PDDocument();
        PDPage page = new PDPage(PDRectangle.A4);
        helloPdf.addPage(page);

        PDPageContentStream contentStream = new PDPageContentStream(helloPdf, page);
        contentStream.beginText();
        contentStream.setFont(PDType1Font.HELVETICA, 10);
        contentStream.newLineAtOffset(10, 100);
        contentStream.showText("Hello PDF World!!!");
        contentStream.endText();
        contentStream.close();

        helloPdf.save(new File("/Users/benito/Desktop/simple.pdf"));
        helloPdf.close();
    }
}
